config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "/restricted", to: "pages#restricted"
  # get 'listings/index', as: "listings"
  #   #=> same as get "/listings", to "listings#index", however must have the index parameter to work
  get '/listings', to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get '/listings/new', to: "listings#new", as: "new_listing"
  get '/listings/:id', to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"
  get '/listings/:id/edit', to: "listings#edit", as: "edit_listing"

  get "/payments/success/:id", to: "payments#success", as: "payments_success"
  post "/payments/webhook", to: "payments#webhook"

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :listings_features, dependent: :destroy
    # dependent: :destroy -> if listing is deleted then listings_feature related to that listing is deleted
  has_many :features, through: :listings_features



  # conditions very loved, gently used, well looked after, brand new
  # enum condition: {"very loved" => 1, "gently used" => 2, "well looked after" => 3, "brand new" => 4}
  enum condition: {very_loved: 1, loved: 2, well_looked_after: 3, brand_new: 4}
  has_one_attached :picture

  #validation
    # ensure specified columns are present. If not then listng is not valid. Therefore will not save to database.
  validates :title, :description, :price, :condition, presence: true
  validates :title, length: {minimum: 4}

  # Sanitise data with lifecycle hooks
  before_save :remove_whitespace, :remove_covid
  before_validation :convert_price_to_cents, if: :price_changed?
    # if: :price_changed? -> required as otherwise price will continously be multiplied by 100 every time price is loaded in when updating listing.

  private

  def remove_whitespace
    self.title = self.title.strip
    self.description = self.description.strip
  end

  def remove_covid
      # where is title appears covid sub with pfizer
      # /covid/i case insensitive covid
        # i -> case insensitive
    self.title = self.title.gsub(/covid/i, "pfizer")
    self.description = self.description.gsub(/covid/i, "pfizer")
  end

  def convert_price_to_cents
    # grab attribute before changed into integer
      # .attributes_before_type_cast -> before conversion into an integer grab the raw data key price from this hash.
      # all attributes come into forms as string then are converted into column value
    self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # before execution any action authenticate users except on the specified actions
  before_action :authenticate_user!, except: [:index, :show] #=> checks is there a user logged in, if not redirect to sign in page
  before_action :set_listing, only: [:show, :edit, :update, :destroy] #=> set instance variable @listing so actions can access all listings variable
  before_action :authorize_user, only: [:edit, :update, :destroy] #=> check if the listing's user id equals the current user id. If not flash alert and redirect.
  before_action :set_form_vars, only: [:new, :edit]
  def index
    @listings = Listing.all
  end

  def show
    #create session -> use Stripe gem -> use Checkout function -> use session function with Checkout function
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user && current_user.email, #=> requires user be logged in
      line_items: [
        {
          name: @listing.title,
          description: @listing.description,
          amount: @listing.price,
          currency: 'aud',
          quantity: 1
        }
      ],
      payment_intent_data: {
        metadata: {
          # this sends the below data to stripe and when data is retrieved, a row can be created in the database to track this. i.e. that the customer has made a payment and what they've bought.
          user_id: current_user && current_user.id,
          listing_id: @listing.id
        }
      },
      # as there is a redirection to Stripe's website and then a redirection back after processing of payment. URLs can be added for re-direction.
      success_url: "#{root_url}payments/success/#{@listing.id}",
      cancel_url: root_url
    )

    # 'session' object has an id when created. So this can be saved by instance varaible for wider access.
    @session_id = session.id
  end

  def new
    # so that there is a partial to pick up errors. There won't be errors on an empty listing
    @listing = Listing.new
  end

  def create
    # # possible passing of user id when creation of new listing. Same thing must be done for update
    # @listing = Listing.new(category_id: params[:category_id])
    # @listing = Listing.new(listing_params)
    # As user has many listings, create new listing by accessing the Current_users listings
      # create listing associated with the current logged in user.
    @listing = current_user.listings.new(listing_params)
    if @listing.save
        redirect_to @listing, notice: "Listing successfully created"
    else
      set_form_vars
      render "new", status: 422
    end
  end

  def edit

  end

  def update
    @listing.update(listing_params)
    if @listing.save
        redirect_to @listing, notice: "Listing successfully updated"
    else
      set_form_vars
      render "edit", status: 422
    end
  end

  def destroy
      @listing.destroy
      redirect_to listings_path, notice: "Listing Sucessfully Deleted"
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :price, :category_id, :condition, :description, :picture, feature_ids: [])
      # feature_ids: [] -> must have default value of empty array and speifies that it is an array
  end

  def authorize_user
    if @listing.user_id != current_user.id
      # flash[:alert] = "You don't have permission to do that"
      redirect_to listing_path, alert: "You don't have permission to do that"
    end
  end
  

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def set_form_vars
    @categories = Category.all
    @conditions = Listing.conditions.keys
    @features = Feature.all
  end

end

app/helpers/listings_helper.rb
module ListingsHelper

    # capitalizes every word in string
    def format_condition(condition)
        # condition.gsub("_"," ")
        # arr = condition.split("_").map do |word|
        #     word.capitalize
        # end
        # arr.join(" ")
        # condition.split("_").map(&:capitalize).join(" ")
        condition.split("_").map {|word| word.capitalize}.join(" ")
    end
    def format_price(price)
        "$#{price / 100.0}"
    end
end

app/views/listings/_form.html.erb
<%= form_with model: @listing, local: true do |f| %>
<% if @listing.errors.any? %>
<div class="alert alert-danger alert-dismissable fade show" role="alert">
    <h3><%= pluralize(@listing.errors.count, "error") %> prohibited this listing form being saved</h3>
    <ul>
        <% @listing.errors.each do |message| %>
        <li><%= message.full_message %></li>
        <% end %>
    </ul>
    <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<% end %>


<div class="form-group mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title %>
</div>

<div class="form-group mb-3">
    <%= f.label :price, class: "form-label" %>
    <%= f.number_field :price, step: "0.01" %>
    <%# step: "0.01" -> changes the increment of the number field %>
</div>

<div class="form-group mb-3">
    <%= f.label :category_id, class: "form-label" %>
    <%= f.select :category_id, @categories.map {|c| [c.name.titleize, c.id]}, class: "form-select" %>
</div>

<h5 class="mb-3 me-2">Condition</h5>
<% @conditions.each do |option| %>
<%= f.label :condition, format_condition(option), class: "form-label me-1" %>
<%= f.radio_button :condition, option, class: "me-2" %>
<% end %>

<h5 class="mb-3 me-2">Features</h5>
<div class="form-check form-check-line mb-3 me-2">
    <%= f.collection_check_boxes :feature_ids, @features, :id, :name do |b| %>
    <%# 
    collcetion of checkboxes for feature_ids, 
    load in @features, 
    select id, 
    see feature name,
    block do seperate out label and check box and apply style
    |b| -> conventions for sub-form
     %>

    <%= b.label class: "form-check-label" %>
    <%# style form label %>
    <%= b.check_box class: "form-check-line mr-2" %>
    <%# style form checkbox %>
    <% end %>


</div>

<div class="form-group mb-3">
    <%= f.label :picture, class: "form-label" %>
    <%= f.file_field :picture, accept: "image/png,image/jpg,image/jpeg" %>
</div>

<div class="form-group mb-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control" %>
</div>

<div class="actions">
    <%= f.submit %>
</div>

<% end %>

app/views/listings/edit.html.erb
<h1>Update Listing</h1>
<%= render "form" %>

<%= link_to "Home", root_path %>

app/views/listings/index.html.erb
<h1 class="hero-title text-center">Listings</h1>

<section class="container">
    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-4">
        <% @listings.each do |listing| %>
        <div class="col mb-4">
            <div class="card border-dark h-100">
                <% if listing.picture.attached? %>
                <%= image_tag listing.picture, class: "thumbnail card-img top", alt: listing.title %>
                <% else %>
                <%= image_tag "toy-car.jpg", class: "thumbnail card-img top", alt: "toy car" %>
                <% end %>
                <div class="card-body">
                    <h5><%= listing.title %></h5>
                    <p class="card-text text-secondary"><%= listing.description %></p>
                    <div class="d-flex justify-content-between">
                        <%= link_to "See more", listing_path(listing.id), class: "btn btn-outline-primary" %>
                        <h5><%= format_price(listing.price) %></h5>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</section>

app/views/listings/new.html.erb
<h1>Create Listing</h1>
<%= render "form" %>

<%= link_to "Home", root_path %>

app/views/listings/show.html.erb
<section class="container d-flex flex-column flex-md-row px-2 my-2 my-md-2">
    <div class="content col-12 col-md-12 col-lg-8 p-0 pr-md-3">
        <div class="col-12 p-0 main-preview mb-4">
            <% if @listing.picture.attached? %>
            <%= image_tag @listing.picture, class: "thumbnail card-img top", alt: @listing.title %>
            <% else %>
            <%= image_tag "toy-car.jpg", class: "thumbnail card-img top", alt: "toy car" %>
            <% end %>
        </div>
    </div>
    <div class="sidebar col-lg-4 p-0 mx-2 d-md-block">
        <h1 class="mb-sm-2 mb-md-5"><%= @listing.title %></h1>

        <h2 class="mb-2">Category: <%= @listing.category.name %></h2>

        <% @listing.features.each do |feature| %>
        <span class="badge rounded-pill bg-info"><%= feature.name %></span>
        <% end %>

        <h4 class="text-muted mb-3">Condition: <%= format_condition(@listing.condition) %></h4>

        <h5 class="text-muted mb-3">Price: <%= format_price(@listing.price) %></h5>

        <p><%= @listing.description %></p>

        <% if current_user && @listing.sold == false %>
        <button class="btn btn-primary mb-3 pr-2" data-stripe="payment">Buy:
            <%= format_price(@listing.price) %></button>
        <% elsif @listing.sold %>
        <button class="btn btn-secondary" disabled>SOLD</button>
        <% else %>
        <%= button_to "Login to buy", new_user_session_path, class: "btn btn-info" %>
        <% end %>

        <div class="container">
            <% if current_user && current_user.id == @listing.user_id %>
            <div class="d-flex justify-content-equally">
                <%= link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-warning me-2" %>
                <%= button_to "Delete", {action: "destroy", id: @listing.id}, form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: "btn btn-danger" %>
            </div>
            <% end %>
        </div>
    </div>

</section>

<%# when button is clicked -> redirect to the session that corresponds with the session id %>
<script src="https://js.stripe.com/v3/"></script>
<script>
    document
        .querySelector("[data-stripe='payment']") // => find button
        .addEventListener("click", () => {
            const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key)%>");
            stripe.redirectToCheckout({
                sessionId: "<%= @session_id %>"
            })
        }) // listening for click event
</script>