config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "/restricted", to: "pages#restricted"
  # get 'listings/index', as: "listings"
  #   #=> same as get "/listings", to "listings#index", however must have the index parameter to work
  get '/listings', to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get '/listings/new', to: "listings#new", as: "new_listing"
  get '/listings/:id', to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"
  get '/listings/:id/edit', to: "listings#edit", as: "edit_listing"

  get "/payments/success/:id", to: "payments#success", as: "payments_success"
  post "/payments/webhook", to: "payments#webhook"

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-md sticky-top">
    <div class="container-fluid">
        <%= link_to "Toys-Is-Us", root_path, class: "navbar-brand" %>
    </div>

    <ul class="navbar-nav me-5-lg">
        <li class="nav-item">
            <%= link_to "All Listings", listings_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Create Listing", new_listing_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
    </ul>
</nav>